import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout/Layout";
import AuthProvider from "@/context/AuthContext";
import CarProvider from "@/context/CarContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "carStore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <AuthProvider>
          <CarProvider>
            <Layout />
            {children}
          </CarProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
